Repository Loopz-Official/LOOPZ-BE, pull requests merged in 2025-07, with the labels that each got.

#60 feat: 모니터링 서버와 연동
  build.gradle
  loopz-authorization/src/main/java/kr/co/loopz/authorization/config/AuthorizationSecurityConfig.java
  loopz-backend/src/main/resources/application.yml
  loopz-common/build.gradle
  loopz-common/src/main/java/kr/co/loopz/common/handler/ResponseInterceptor.java
Labels: 🌏 Deploy

#63 fix: 동일 주소 예외 수정
  loopz-user-service/src/main/java/kr/co/loopz/user/apiExternal/UserAddressController.java
  loopz-user-service/src/main/java/kr/co/loopz/user/apiExternal/UserDetailInfoController.java
  loopz-user-service/src/main/java/kr/co/loopz/user/converter/UserConverter.java
  loopz-user-service/src/main/java/kr/co/loopz/user/domain/UserEntity.java
  loopz-user-service/src/main/java/kr/co/loopz/user/dto/response/DetailInfoUpdateResponse.java
  loopz-user-service/src/main/java/kr/co/loopz/user/exception/UserErrorCode.java
  loopz-user-service/src/main/java/kr/co/loopz/user/exception/UserException.java
  loopz-user-service/src/main/java/kr/co/loopz/user/repository/AddressRepository.java
  loopz-user-service/src/main/java/kr/co/loopz/user/service/UserAddressService.java
  loopz-user-service/src/main/java/kr/co/loopz/user/service/UserDetailInfoService.java
  loopz-user-service/src/main/java/kr/co/loopz/user/service/UserNickNameService.java
Labels: 🔨 Refactor

#72 fix: 오브제보드 total count 버그 수정
  loopz-product-service/src/main/java/kr/co/loopz/object/converter/ObjectConverter.java
  loopz-product-service/src/main/java/kr/co/loopz/object/service/ObjectService.java
Labels: 🐛 bug

#77 fix: 장바구니 수량 변경 로직 수정
  loopz-product-service/src/main/java/kr/co/loopz/object/service/CartService.java
  loopz-user-service/src/main/java/kr/co/loopz/user/apiExternal/UserAddressController.java
  loopz-user-service/src/main/java/kr/co/loopz/user/converter/UserConverter.java
  loopz-user-service/src/main/java/kr/co/loopz/user/dto/response/AddressResponse.java
  loopz-user-service/src/main/java/kr/co/loopz/user/repository/AddressRepository.java
  loopz-user-service/src/main/java/kr/co/loopz/user/service/UserAddressService.java
Labels: fix

#78 feat: 닉네임 제한 강화
  loopz-user-service/src/main/java/kr/co/loopz/user/service/UserNickNameService.java
Labels: ✨ feature

#82 fix: liked 여부를 primitive 타입으로 수정
  loopz-product-service/src/main/java/kr/co/loopz/object/dto/response/ObjectResponse.java
Labels: 🐛 bug

#85 feat: my page 유저 정보 조회 엔드포인트 구현
  loopz-user-service/src/main/java/kr/co/loopz/user/apiExternal/UserController.java
  loopz-user-service/src/main/java/kr/co/loopz/user/converter/UserConverter.java
  loopz-user-service/src/main/java/kr/co/loopz/user/dto/response/UserInfoResponse.java
  loopz-user-service/src/main/java/kr/co/loopz/user/service/UserService.java
Labels: ✨ feature

#89 fix: 최신순 정렬
  loopz-product-service/src/main/java/kr/co/loopz/object/service/AbstractObjectService.java
Labels: fix

#94 feat: 주문 상품 정보 반환
  loopz-product-service/src/main/java/kr/co/loopz/object/apiExternal/ObjectController.java
  loopz-product-service/src/main/java/kr/co/loopz/object/converter/ObjectConverter.java
  loopz-product-service/src/main/java/kr/co/loopz/object/dto/request/ObjectInfoRequest.java
  loopz-product-service/src/main/java/kr/co/loopz/object/dto/response/OrderObjectInfoResponse.java
  loopz-product-service/src/main/java/kr/co/loopz/object/exception/ObjectErrorCode.java
  loopz-product-service/src/main/java/kr/co/loopz/object/service/AbstractObjectService.java
  loopz-product-service/src/main/java/kr/co/loopz/object/service/CartService.java
  loopz-product-service/src/main/java/kr/co/loopz/object/service/ObjectDetailService.java
Labels: ✨ feature

#99 fix: filterCount 수정
  loopz-product-service/src/main/java/kr/co/loopz/object/apiExternal/ObjectController.java
  loopz-product-service/src/main/java/kr/co/loopz/object/apiInternal/InternalObjectController.java
  loopz-product-service/src/main/java/kr/co/loopz/object/domain/ObjectEntity.java
  loopz-product-service/src/main/java/kr/co/loopz/object/dto/request/DeleteCartItemRequest.java
  loopz-product-service/src/main/java/kr/co/loopz/object/dto/request/FilterRequest.java
  loopz-product-service/src/main/java/kr/co/loopz/object/dto/request/SearchFilterRequest.java
  loopz-product-service/src/main/java/kr/co/loopz/object/dto/response/BoardResponse.java
  loopz-product-service/src/main/java/kr/co/loopz/object/repository/ObjectRepository.java
  loopz-product-service/src/main/java/kr/co/loopz/object/repository/query/ObjectQueryRepository.java
  loopz-product-service/src/main/java/kr/co/loopz/object/repository/query/ObjectQueryRepositoryImpl.java
  loopz-product-service/src/main/java/kr/co/loopz/object/service/AbstractObjectService.java
  loopz-product-service/src/main/java/kr/co/loopz/object/service/ObjectBoardService.java
  loopz-product-service/src/main/java/kr/co/loopz/object/service/ObjectListService.java
  loopz-product-service/src/main/java/kr/co/loopz/object/service/ObjectSearchService.java
  loopz-search-service/src/main/java/kr/co/loopz/search/dto/request/SearchFilterRequest.java
  loopz-search-service/src/main/java/kr/co/loopz/search/dto/response/BoardResponse.java
Labels: fix

#105 feat : apiExternal에 대해 AOP 실행시간 추가
  loopz-common/build.gradle
  loopz-common/src/main/java/kr/co/loopz/common/config/TimeTraceAop.java
Labels: ✨ feature

#113 feat: 주문 상세보기
  loopz-order-service/src/main/java/kr/co/loopz/order/apiExternal/OrderController.java
  loopz-order-service/src/main/java/kr/co/loopz/order/client/ObjectClient.java
  loopz-order-service/src/main/java/kr/co/loopz/order/client/UserClient.java
  loopz-order-service/src/main/java/kr/co/loopz/order/converter/OrderConverter.java
  loopz-order-service/src/main/java/kr/co/loopz/order/domain/Order.java
  loopz-order-service/src/main/java/kr/co/loopz/order/dto/response/CartItemResponse.java
  loopz-order-service/src/main/java/kr/co/loopz/order/dto/response/CartWithQuantityResponse.java
  loopz-order-service/src/main/java/kr/co/loopz/order/dto/response/InternalAddressResponse.java
  loopz-order-service/src/main/java/kr/co/loopz/order/dto/response/OrderDetailResponse.java
  loopz-order-service/src/main/java/kr/co/loopz/order/dto/response/OrderListResponse.java
  loopz-order-service/src/main/java/kr/co/loopz/order/dto/response/PurchasedObjectResponse.java
  loopz-order-service/src/main/java/kr/co/loopz/order/exception/OrderErrorCode.java
  loopz-order-service/src/main/java/kr/co/loopz/order/repository/OrderItemRepository.java
  loopz-order-service/src/main/java/kr/co/loopz/order/repository/OrderRepository.java
  loopz-order-service/src/main/java/kr/co/loopz/order/service/OrderDetailService.java
  loopz-order-service/src/main/java/kr/co/loopz/order/service/OrderListService.java
  loopz-product-service/src/main/java/kr/co/loopz/object/apiInternal/InternalObjectController.java
  loopz-product-service/src/main/java/kr/co/loopz/object/domain/CartItem.java
  loopz-product-service/src/main/java/kr/co/loopz/object/service/CartService.java
  loopz-user-service/src/main/java/kr/co/loopz/user/apiInternal/InternalUserController.java
  loopz-user-service/src/main/java/kr/co/loopz/user/service/UserAddressService.java
Labels: ✨ feature

#116 fix: orderDate 수정
  loopz-order-service/src/main/java/kr/co/loopz/order/converter/OrderConverter.java
  loopz-order-service/src/main/java/kr/co/loopz/order/domain/Order.java
  loopz-order-service/src/main/java/kr/co/loopz/order/dto/response/OrderListResponse.java
  loopz-order-service/src/main/java/kr/co/loopz/order/dto/response/PurchasedObjectResponse.java
Labels: ✨ feature

#120 fix: my 응답 수정
  loopz-user-service/src/main/java/kr/co/loopz/user/dto/response/UserInfoResponse.java
Labels: fix

#136 fix: 닉네임 제한 강화
  loopz-user-service/src/main/java/kr/co/loopz/user/service/UserNickNameService.java
Labels: fix

#142 fix(search): 검색 시 필터 쿼리로 받도록 수정
  loopz-search-service/src/main/java/kr/co/loopz/search/apiExternal/SearchController.java
  loopz-search-service/src/main/java/kr/co/loopz/search/dto/request/SearchFilterRequest.java
  loopz-search-service/src/main/java/kr/co/loopz/search/dto/request/enums/SortType.java
Labels: fix

#135 feat: 주문 생성 충돌 Aop 추가
  build.gradle
  loopz-common/build.gradle
  loopz-order-service/build.gradle
  loopz-order-service/src/main/java/kr/co/loopz/order/aop/RetryAspect.java
  loopz-order-service/src/main/java/kr/co/loopz/order/aop/RetryOrder.java
  loopz-order-service/src/main/java/kr/co/loopz/order/service/OrderService.java
  loopz-order-service/src/test/java/kr/co/loopz/OrderServiceTestApplication.java
  loopz-order-service/src/test/java/kr/co/loopz/order/util/OrderNumberCollisionTest.java
  loopz-order-service/src/test/java/kr/co/loopz/order/util/OrderNumberCollisionWithAop.java
  loopz-order-service/src/test/resources/application-test.yml
Labels: ✨ feature

#145 fix: test server 카프카와 연결하도록 CD 스크립트 수정
  test-server-docker-compose.yml
Labels: infra

#146 chore: Redis를 Elastic Cache로 이전
  loopz-backend/src/main/resources/application-local.yml
  loopz-backend/src/main/resources/application.yml
  loopz-common/src/main/java/kr/co/loopz/common/redis/config/RedisConfig.java
  loopz-product-service/src/main/java/kr/co/loopz/object/config/RedissonConfig.java
Labels: infra

#148 fix: 최근 검색어 삭제 수정
  loopz-search-service/src/main/java/kr/co/loopz/search/apiExternal/SearchController.java
  loopz-search-service/src/main/java/kr/co/loopz/search/exception/SearchErrorCode.java
  loopz-search-service/src/main/java/kr/co/loopz/search/repository/SearchRepository.java
  loopz-search-service/src/main/java/kr/co/loopz/search/service/SearchService.java
Labels: fix
